name: unwaver
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_generative_ai: ^0.4.4
  provider: ^6.1.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  # Added for environment variables
  flutter_dotenv: ^5.2.0 
  fl_chart: ^0.66.0
  lottie: ^3.3.2
  shared_preferences: ^2.5.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env 
    - assets/animations/

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/Unwaver_App_Icon.png
  min_sdk_android: 21