name: unwaver
description: A purpose-driven planner that seamlessly integrates habits, tasks, and native calendar sync to help users build their perfect daily routine.

# The following line prevents accidental publishing of your proprietary code to the public Dart package repository (pub.dev).
# It does NOT restrict you from publishing the app to the iOS App Store, Android Google Play, or the Web.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # --- Core UI & Icons ---
  cupertino_icons: ^1.0.8
  
  # --- Firebase & Auth ---
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  flutter_facebook_auth: ^7.1.1
  
  # --- State Management & Architecture ---
  provider: ^6.1.1
  shared_preferences: ^2.5.4
  flutter_dotenv: ^5.2.0 
  
  # --- AI ---
  google_generative_ai: ^0.4.4
  
  # --- Schedule & Calendar ---
  table_calendar: ^3.2.0
  intl: ^0.20.2
  device_calendar: ^4.3.1
  
  # --- UI Components & Animations ---
  fl_chart: ^0.66.0
  lottie: ^3.3.2

  # --- For Biometric Authentication ---
  local_auth: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env 
    - assets/animations/loading.json

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/Unwaver_App_Icon.png
  min_sdk_android: 21